### ISSUE TITLE
[FR] Subsume capability for Azure SQL MASB Failover Groups

### ISSUE THREAD

**Issue by claassen** [pivotal/cloud-service-broker#105]
**Is your feature request related to a problem? Please describe.**
Would like a streamlined way for users to migrate from existing MASB Azure SQL Failover group to CSB Failover Group instance

**Describe the solution you'd like**
Something similar to the existing csb-masb-mssql-db-subsume service

**Describe alternatives you've considered**
Exporting data from existing database, creating new CSB instances and importing the data to the new instance.

**Additional Context**

**Priority**
High

**Priority Context**
A solution with minimal downtime for migrating from MASB to CSB Azure SQL failover groups is required for minimal application downtime and business disruption.

**Platform** 
Azure

**Applicable Services**
Azure SQL Failover Group

**Comment by omerbensaadon** [comment]
@drebake is this relevant to your team?

**Comment by drebake** [comment]
Yes it would. We will have some MASB FOG that we will need to migrate. I haven't viewed that portion of the documentation or started testing the db migration process yet... I'm planning on tackling that subject and documenting our strategy in two weeks.

**Comment by erniebilling** [comment]
This feature is currently in progress.

**Comment by omerbensaadon** [comment]
Currently blocked by https://github.com/terraform-providers/terraform-provider-azurerm/issues/8892

**Comment by omerbensaadon** [comment]
While exploring the possibility to create a PR to fix terraform-providers/terraform-provider-azurerm#8892, @erniebilling found a fix! 

We are unblocked and this is being worked now. CC: @drebake

**Comment by erniebilling** [comment]
Available in https://github.com/pivotal/cloud-service-broker/releases/tag/v0.8.2-beta

See https://github.com/pivotal/cloud-service-broker/blob/master/docs/subsume-masb-mssql-db-fog.md for docs.

**Comment by drebake** [comment]
@erniebilling 
If the server_pair is already configured in the "Existing SQL Server Pair Credentials" for the "Azure SQL Failover Group Config And Plans On Pre-configured Server Pairs (csb-azure-mssql-db-failover-group)" service, do we still have to provide the FOG-SERVER-PAIR admin_username and admin_password while creating the service or can we simply specify the server pair?

The reason I'm asking is because the admin_username and admin_password are usually not information that the devops team creating the service would have in hand.

**Comment by erniebilling** [comment]
@drebake The answer is no. If the credentials are already configured globally for the service, only the server_pair value is required.
